# .travis.yml
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

language: c
sudo: required
env:
  global:
    secure: R5Ibbkb/PWqB5WVwld/4Upy1juOW3CzWv7RqO5bbshfLwDhfdKYm8SGf+J7Qd9JlYXgizQDPooR7Gk3eT/ls1q6Fxi4kboHSQbbt7jeicjrWMARB6SwcVca/UlHasAAyu6Te83jOin34pmG/as3HZoJnBUnjCMrB32cjb3sye8zK4bxBflRnlFMqvTrSNr7HOBRlpowhd6ZtiMP+/GPgjkj67dym9PrOH8pVPVyAJZsEdqFXBqvVTjTeoPOLDYC/laezsceSjaHERTOfGCwfqSG48WGpQEnj9Nmiy5QYQrMUjoJZBzWtRE8kakTh2JK3PF9SK3nT9EgZCR0F4l6eX8yHEytHXlJkxKFOtowZuCotVFhmT0ljUqflYAjsOz3+P0e5Jjk5N/o5mhOcCA7ulQVz/T8xPZZAqWvobQxGhpMMsySWEl++afuKHG/md8UzncUHKGiLO7Yz+zT7VK5FWINX57ElsxkZ0MhhjkBHXERnjhbchN3sLJVkGCPMRcDAkKac+/lKZCNrprpSE9MkshbV+OTYaIEqZjWrQEtOkNvBRDcNivWo5MlKMkNgwjITYPHo383k7CVoMZp9btm5IQEhXRKJZEUa7AJgv078pcyitvhNv0Xabsnop+eE5d+5IZAcBwHg/CyjqQy8ALei0WOfXVA3jdAadtxqU9U6cSk=
branches:
  only: master
before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
install:
  - ./travis-tool.sh install_deps
script: ./travis-tool.sh run_tests
after_failure:
  - ./travis-tool.sh dump_logs
after_success:
  - cd /home/travis/build/njanetos/
  - R CMD Rd2pdf drugs
  - git clone git@github.com:njanetos/drugs.git drugs-doc
  - cd drugs-doc
  - git checkout gh-pages
  - mv ../drugs.pdf .
  - git add drugs.pdf
  - git commit -m "updated reference manual"
  - git push origin gh-pages
notifications:
  email:
    on_success: change
    on_failure: change
