# .travis.yml
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

language: c
sudo: required
env:
  global:
    secure: R5Ibbkb/PWqB5WVwld/4Upy1juOW3CzWv7RqO5bbshfLwDhfdKYm8SGf+J7Qd9JlYXgizQDPooR7Gk3eT/ls1q6Fxi4kboHSQbbt7jeicjrWMARB6SwcVca/UlHasAAyu6Te83jOin34pmG/as3HZoJnBUnjCMrB32cjb3sye8zK4bxBflRnlFMqvTrSNr7HOBRlpowhd6ZtiMP+/GPgjkj67dym9PrOH8pVPVyAJZsEdqFXBqvVTjTeoPOLDYC/laezsceSjaHERTOfGCwfqSG48WGpQEnj9Nmiy5QYQrMUjoJZBzWtRE8kakTh2JK3PF9SK3nT9EgZCR0F4l6eX8yHEytHXlJkxKFOtowZuCotVFhmT0ljUqflYAjsOz3+P0e5Jjk5N/o5mhOcCA7ulQVz/T8xPZZAqWvobQxGhpMMsySWEl++afuKHG/md8UzncUHKGiLO7Yz+zT7VK5FWINX57ElsxkZ0MhhjkBHXERnjhbchN3sLJVkGCPMRcDAkKac+/lKZCNrprpSE9MkshbV+OTYaIEqZjWrQEtOkNvBRDcNivWo5MlKMkNgwjITYPHo383k7CVoMZp9btm5IQEhXRKJZEUa7AJgv078pcyitvhNv0Xabsnop+eE5d+5IZAcBwHg/CyjqQy8ALei0WOfXVA3jdAadtxqU9U6cSk=
branches:
  only: master
before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
install:
  - ./travis-tool.sh install_deps
script: ./travis-tool.sh run_tests
after_failure:
  - ./travis-tool.sh dump_logs
after_success:
  - sudo apt-get install texinfo texlive-base texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra
  - cd /home/travis/build/njanetos/
  - R CMD Rd2pdf drugs
  - R CMD INSTALL drugs
  - Rscript -e "install.packages('rmarkdown')"
  - Rscript -e "library('rmarkdown'); for(file.name in dir(path = 'drugs/vignettes/', pattern = '*.Rmd')) { render(paste('drugs/vignettes', file.name, sep='/'), output_file = gsub('Rmd', 'html', file.name), output_format = 'html_document') }"
  - git clone https://${GH_TOKEN}@github.com/njanetos/drugs.git drugs-doc
  - cd drugs-doc
  - git config user.name "Jan Tilly"
  - git config user.email "jantilly@gmail.com"
  - git checkout gh-pages
  - git pull origin gh-pages
  - mv ../drugs.pdf .
  - mv ../*.html .
  - git add drugs.pdf *.html
  - git commit -m "updated reference manual and vignettes"
  - git push origin gh-pages
notifications:
  email:
    on_success: change
    on_failure: change
